version: '3.7'
services:
    app:
        image: laravelphp
        container_name: bus_booking_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8890:8890"
        networks:
            - app-network
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        container_name: bus_booking_db
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: bus_booking_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3307:3307"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    db_data:
